# Generated by Django 4.1.1 on 2022-09-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=200)),
                ('cam_id', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficTimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('traffic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffics.trafficdata')),
            ],
        ),
    ]
